/**
 * [GENERATED BY scripts/gen-model.mjs - DO NOT EDIT MANUALLY]
 * pyDEXPI 1.2.0 Enumeration types.
 */

export type ChamberFunctionClassification = 'NULL' | 'Cooling' | 'Heating' | 'Processing' | 'Tempering';
export type CompositionBreakClassification = 'NULL' | 'CompositionBreak' | 'NoCompositionBreak';
export type ConfidentialityClassification = 'NULL' | 'ConfidentialInformation' | 'NonConfidentialInformation';
export type DetonationProofArtefactClassification = 'NULL' | 'DetonationProofArtefact' | 'NonDetonationProofArtefact';
export type ExplosionProofArtefactClassification = 'NULL' | 'ExplosionProofArtefact' | 'NonExplosionProofArtefact';
export type FailActionClassification = 'NULL' | 'FailClose' | 'FailOpen' | 'FailRetainPosition';
export type FireResistantArtefactClassification = 'NULL' | 'FireResistantArtefact' | 'NonFireResistantArtefact';
export type GmpRelevanceClassification = 'NULL' | 'GmpRelevantFunction' | 'NonGmpRelevantFunction';
export type GuaranteedSupplyFunctionClassification = 'NULL' | 'GuaranteedSupplyFunction' | 'NonGuaranteedSupplyFunction';
export type HeatTracingTypeClassification = 'NULL' | 'ElectricalHeatTracingSystem' | 'HeatTracingSystem' | 'NoHeatTracingSystem' | 'SteamHeatTracingSystem' | 'TubularHeatTracingSystem';
export type InsulationBreakClassification = 'NULL' | 'InsulationBreak' | 'NoInsulationBreak';
export type JacketedPipeClassification = 'NULL' | 'JacketedPipe' | 'UnjacketedPipe';
export type LocationClassification = 'NULL' | 'CentralLocation' | 'ControlPanel' | 'Field';
export type NominalDiameterBreakClassification = 'NULL' | 'NoNominalDiameterBreak' | 'NominalDiameterBreak';
export type NominalDiameterStandardClassification = 'NULL' | 'Din2448ObjectDn100' | 'Din2448ObjectDn125' | 'Din2448ObjectDn15' | 'Din2448ObjectDn150' | 'Din2448ObjectDn20' | 'Din2448ObjectDn200' | 'Din2448ObjectDn25' | 'Din2448ObjectDn32' | 'Din2448ObjectDn40' | 'Din2448ObjectDn50' | 'Din2448ObjectDn65' | 'Din2448ObjectDn80' | 'Iso6708ObjectDn100' | 'Iso6708ObjectDn1000' | 'Iso6708ObjectDn1200' | 'Iso6708ObjectDn125' | 'Iso6708ObjectDn1400' | 'Iso6708ObjectDn15' | 'Iso6708ObjectDn150' | 'Iso6708ObjectDn1600' | 'Iso6708ObjectDn20' | 'Iso6708ObjectDn200' | 'Iso6708ObjectDn25' | 'Iso6708ObjectDn250' | 'Iso6708ObjectDn300' | 'Iso6708ObjectDn32' | 'Iso6708ObjectDn350' | 'Iso6708ObjectDn40' | 'Iso6708ObjectDn400' | 'Iso6708ObjectDn450' | 'Iso6708ObjectDn50' | 'Iso6708ObjectDn500' | 'Iso6708ObjectDn600' | 'Iso6708ObjectDn65' | 'Iso6708ObjectDn700' | 'Iso6708ObjectDn80' | 'Iso6708ObjectDn800' | 'Iso6708ObjectDn900' | 'Nps1_s_2Artefact' | 'Nps1_s_4Artefact' | 'Nps10Artefact' | 'Nps12Artefact' | 'Nps14Artefact' | 'Nps16Artefact' | 'Nps18Artefact' | 'Nps1Artefact' | 'Nps1_1_s_2Artefact' | 'Nps1_1_s_4Artefact' | 'Nps20Artefact' | 'Nps24Artefact' | 'Nps2Artefact' | 'Nps2_1_s_2Artefact' | 'Nps3_s_4Artefact' | 'Nps30Artefact' | 'Nps36Artefact' | 'Nps3Artefact' | 'Nps3_1_s_2Artefact' | 'Nps42Artefact' | 'Nps48Artefact' | 'Nps4Artefact' | 'Nps54Artefact' | 'Nps5Artefact' | 'Nps60Artefact' | 'Nps6Artefact' | 'Nps8Artefact';
export type NominalPressureStandardClassification = 'NULL' | 'Class10000PsiArtefact' | 'Class1000KpaArtefact' | 'Class125LbsArtefact' | 'Class15000PsiArtefact' | 'Class1500LbsArtefact' | 'Class150LbsArtefact' | 'Class16BarArtefact' | 'Class20000PsiArtefact' | 'Class2000PsiArtefact' | 'Class2500LbsArtefact' | 'Class250PsiArtefact' | 'Class3000PsiArtefact' | 'Class300LbsArtefact' | 'Class300PsiArtefact' | 'Class315BarArtefact' | 'Class345BarArtefact' | 'Class350BarArtefact' | 'Class4000PsiArtefact' | 'Class400LbsArtefact' | 'Class4500LbsArtefact' | 'Class4500PsiArtefact' | 'Class5000PsiArtefact' | 'Class50BarArtefact' | 'Class517BarArtefact' | 'Class6000PsiArtefact' | 'Class600LbsArtefact' | 'Class690BarArtefact' | 'Class800LbsArtefact' | 'Class800PsiArtefact' | 'Class850KpaArtefact' | 'Class9000LbsArtefact' | 'Class900LbsArtefact' | 'En1333Pn100Artefact' | 'En1333Pn10Artefact' | 'En1333Pn160Artefact' | 'En1333Pn16Artefact' | 'En1333Pn2_c_5Artefact' | 'En1333Pn250Artefact' | 'En1333Pn25Artefact' | 'En1333Pn320Artefact' | 'En1333Pn400Artefact' | 'En1333Pn40Artefact' | 'En1333Pn63Artefact' | 'En1333Pn6Artefact';
export type NumberOfPortsClassification = 'NULL' | 'FourPortValve' | 'ThreePortValve' | 'TwoPortValve';
export type OnHoldClassification = 'NULL' | 'NotOnHold' | 'OnHold';
export type OperationClassification = 'NULL' | 'ContinuousOperation' | 'IntermittentOperation';
export type PipingClassArtefactClassification = 'NULL' | 'NonPipingClassArtefact' | 'PipingClassArtefact';
export type PipingClassBreakClassification = 'NULL' | 'NoPipingClassBreak' | 'PipingClassBreak';
export type PipingNetworkSegmentFlowClassification = 'NULL' | 'DualFlowPipingNetworkSegment' | 'SingleFlowPipingNetworkSegment';
export type PipingNetworkSegmentSlopeClassification = 'NULL' | 'SlopedPipingNetworkSegment' | 'UnslopedPipingNetworkSegment';
export type PortStatusClassification = 'NULL' | 'StatusHighHighHighPort' | 'StatusHighHighPort' | 'StatusHighPort' | 'StatusLowLowLowPort' | 'StatusLowLowPort' | 'StatusLowPort';
export type PrimarySecondaryPipingNetworkSegmentClassification = 'NULL' | 'PrimaryPipingNetworkSegment' | 'SecondaryPipingNetworkSegment';
export type QualityRelevanceClassification = 'NULL' | 'NonQualityRelevantFunction' | 'QualityRelevantFunction';
export type SignalConveyingTypeClassification = 'NULL' | 'CapillarySignalConveying' | 'ConductedRadiationSignalConveying' | 'ElectricalSignalConveying' | 'HydraulicSignalConveying' | 'PneumaticSignalConveying';
export type SiphonClassification = 'NULL' | 'NoSiphon' | 'Siphon';
