#!/usr/bin/env node
/**
 * Generates TypeScript model interfaces, SCHEMA field registry, and URI constants from pyDEXPI metadata.
 * Offline dev-only script. The generated output is committed to source control.
 */

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');

// 1. Run python extraction script
console.log('Extracting pyDEXPI schema via Python...');
const venvPython = path.join(REPO_ROOT, '.venv', 'bin', 'python');
const pyScript = path.join(REPO_ROOT, 'scripts', 'extract_schema.py');
execSync(`"${venvPython}" "${pyScript}"`, { stdio: 'inherit' });

const schemaJsonPath = path.join(REPO_ROOT, 'scripts', 'pydexpi-schema.json');
const schema = JSON.parse(fs.readFileSync(schemaJsonPath, 'utf-8'));

const MODEL_DIR = path.join(REPO_ROOT, 'src', 'model');
const CLASSES_DIR = path.join(MODEL_DIR, 'classes');
fs.mkdirSync(CLASSES_DIR, { recursive: true });

// 2. Generate uris.ts
console.log('Generating src/model/uris.ts...');
const urisContent = `/**
 * [GENERATED BY scripts/gen-model.mjs - DO NOT EDIT MANUALLY]
 * pyDEXPI 1.2.0 URI constants and bidirectional lookups.
 */

export const CLASS_URIS: Record<string, string> = ${JSON.stringify(schema.uris, null, 2)};

export const URI_TO_CLASS: Record<string, string> = Object.fromEntries(
  Object.entries(CLASS_URIS).map(([cls, uri]) => [uri, cls])
);

export function uriForClass(className: string): string {
  return CLASS_URIS[className] || \`http://sandbox.dexpi.org/rdl/\${className}\`;
}

export function classForUri(uri: string): string | undefined {
  return URI_TO_CLASS[uri];
}
`;
fs.writeFileSync(path.join(MODEL_DIR, 'uris.ts'), urisContent, 'utf-8');

// 3. Generate enumerations.ts
console.log('Generating src/model/classes/enumerations.ts...');
let enumsContent = `/**
 * [GENERATED BY scripts/gen-model.mjs - DO NOT EDIT MANUALLY]
 * pyDEXPI 1.2.0 Enumeration types.
 */\n\n`;

for (const [enumName, values] of Object.entries(schema.enums)) {
  const union = values.map((v) => `'${v}'`).join(' | ');
  enumsContent += `export type ${enumName} = ${union || 'string'};\n`;
}
fs.writeFileSync(path.join(CLASSES_DIR, 'enumerations.ts'), enumsContent, 'utf-8');

// 4. Generate base.ts
console.log('Generating src/model/classes/base.ts...');
const baseContent = `/**
 * Core DEXPI primitives, envelope types, and base interfaces.
 */

import type { MultiLanguageString, SingleLanguageString } from './dataTypes';

export type Ref = string;
export type RefList = string[];

export interface ProteusPassthrough {
  attrs?: Record<string, string>;
  extra?: any[];
  childOrder?: string[];
}

export interface DexpiObject {
  id: string;
  uri: string;
  proteusId?: string;
  _proteus?: ProteusPassthrough;
}

export interface PhysicalQuantity {
  value: number | null;
  unit: string;
  uri: string;
}

export type DexpiValue =
  | string
  | number
  | boolean
  | null
  | SingleLanguageString
  | MultiLanguageString
  | PhysicalQuantity
  | CustomAttribute
  | Record<string, unknown>
  | DexpiValue[];

export interface CustomAttribute {
  attributeName: string;
  attributeURI?: string;
  value: DexpiValue;
  format?: string;
  language?: string;
  set?: string;
  unit?: string;
}

export interface CustomAttributeOwner {
  customAttributes?: CustomAttribute[];
}
`;
fs.writeFileSync(path.join(CLASSES_DIR, 'base.ts'), baseContent, 'utf-8');

// 5. Generate dataTypes.ts
console.log('Generating src/model/classes/dataTypes.ts...');
const dataTypesContent = `/**
 * DEXPI string data types.
 */

export interface SingleLanguageString {
  language?: string;
  value: string;
}

export type MultiLanguageString = SingleLanguageString[];
`;
fs.writeFileSync(path.join(CLASSES_DIR, 'dataTypes.ts'), dataTypesContent, 'utf-8');

// 6. Generate physicalQuantities.ts & customization.ts
fs.writeFileSync(
  path.join(CLASSES_DIR, 'physicalQuantities.ts'),
  `export type { PhysicalQuantity } from './base';\n`,
  'utf-8'
);
fs.writeFileSync(
  path.join(CLASSES_DIR, 'customization.ts'),
  `export type { CustomAttribute, CustomAttributeOwner } from './base';\n`,
  'utf-8'
);

// 7. Generate graphics.ts
console.log('Generating src/model/classes/graphics.ts...');
const graphicsContent = `/**
 * DEXPI Graphics and Drawing model.
 */

import type { DexpiObject, Ref } from './base';

export interface Point {
  x: number;
  y: number;
  z?: number;
}

export interface Position {
  location: Point;
  axis?: Point;
  reference?: Point;
}

export interface Extent {
  min: Point;
  max: Point;
}

export interface Presentation {
  r?: number;
  g?: number;
  b?: number;
  lineType?: number | string;
  lineWeight?: number;
}

export interface TextStringFormatSpecification {
  dependantAttribute?: string;
  dependantAttributeContents?: string;
  itemID?: string;
}

export interface Text {
  string: string;
  font?: string;
  height?: number;
  width?: number;
  justification?: string;
  textAngle?: number;
  position?: Position;
  presentation?: Presentation;
  formatSpecification?: TextStringFormatSpecification;
}

export interface TextTemplate {
  string: string;
  font?: string;
  height?: number;
  width?: number;
  justification?: string;
  position?: Position;
  presentation?: Presentation;
}

export interface PolyLine {
  points: Point[];
  presentation?: Presentation;
}

export interface Polygon {
  points: Point[];
  presentation?: Presentation;
}

export interface Circle {
  radius: number;
  position?: Position;
  presentation?: Presentation;
}

export interface Ellipse {
  majorRadius: number;
  minorRadius: number;
  position?: Position;
  presentation?: Presentation;
}

export interface EllipseArc {
  majorRadius: number;
  minorRadius: number;
  startAngle: number;
  endAngle: number;
  position?: Position;
  presentation?: Presentation;
}

export type GraphicPrimitive =
  | PolyLine
  | Polygon
  | Circle
  | Ellipse
  | EllipseArc
  | Text
  | TextTemplate;

export interface ShapeUsage extends DexpiObject {
  shape?: Ref;
  position?: Position;
  rotation?: number;
  scaleX?: number;
  scaleY?: number;
  isMirrored?: boolean;
}

export interface Label extends DexpiObject {
  componentClass?: string;
  componentClassUri?: string;
  texts: Text[];
  lines?: PolyLine[];
  position?: Position;
}

export interface Static extends DexpiObject {
  elements: (ShapeUsage | GraphicPrimitive)[];
}

export interface RepresentationGroup extends DexpiObject {
  represents?: Ref;
  groups: (Static | Label | RepresentationGroup)[];
  nodePositions?: any[];
}

export interface DrawingBorder extends DexpiObject {
  elements: (GraphicPrimitive | Label | Static)[];
}

export interface Diagram extends DexpiObject {
  name?: string;
  minX?: number;
  minY?: number;
  maxX?: number;
  maxY?: number;
  backgroundColor?: Presentation;
  represents?: Ref;
  groups: (RepresentationGroup | Label | DrawingBorder | Static | any)[];
  nodePositions?: any[];
}

export interface Shape extends DexpiObject {
  componentName?: string;
  componentClass?: string;
  componentClassUri?: string;
  primitives: GraphicPrimitive[];
  attributes?: Record<string, any>;
}

export type TaggedPlantItemShape = Shape;
export type PipingComponentShape = Shape;
export type InstrumentShape = Shape;
export type ActuatingSystemComponentShape = Shape;

export interface ShapeCatalogue extends DexpiObject {
  name?: string;
  shapes: Shape[];
}
`;
fs.writeFileSync(path.join(CLASSES_DIR, 'graphics.ts'), graphicsContent, 'utf-8');

// 8. Generate plantStructure.ts
console.log('Generating src/model/classes/plantStructure.ts...');
const plantStructureContent = `/**
 * DEXPI Plant Structure items.
 */

import type { DexpiObject, CustomAttributeOwner, Ref } from './base';

export interface PlantStructureItem extends DexpiObject, CustomAttributeOwner {
  structureName?: string;
  structureIdentifier?: string;
  parentStructure?: Ref;
}

export type Enterprise = PlantStructureItem;
export type IndustrialComplex = PlantStructureItem;
export type PlantArea = PlantStructureItem;
export type PlantSection = PlantStructureItem;
`;
fs.writeFileSync(path.join(CLASSES_DIR, 'plantStructure.ts'), plantStructureContent, 'utf-8');

// 9. Generate metaData.ts
console.log('Generating src/model/classes/metaData.ts...');
const metaDataContent = `/**
 * DEXPI MetaData container.
 */

import type { DexpiObject, CustomAttributeOwner, DexpiValue } from './base';

export interface MetaData extends DexpiObject, CustomAttributeOwner {
  approvalDateRepresentation?: string;
  approvalDescription?: any;
  approverName?: string;
  archiveNumber?: string;
  checkerName?: string;
  confidentiality?: string;
  creationDateRepresentation?: string;
  creatorName?: string;
  designerName?: string;
  drafterName?: string;
  drawingName?: string;
  drawingNumber?: string;
  drawingSubTitle?: any;
  enterpriseIdentificationCode?: string;
  enterpriseName?: string;
  fileName?: string;
  industrialComplexIdentificationCode?: string;
  industrialComplexName?: string;
  lastModificationDateRepresentation?: string;
  plantAreaIdentificationCode?: string;
  plantSectionIdentificationCode?: string;
  plantSectionName?: string;
  plantSystemIdentificationCode?: string;
  plantSystemName?: string;
  plantTrainIdentificationCode?: string;
  plantTrainName?: string;
  processPlantIdentificationCode?: string;
  processPlantName?: string;
  projectName?: string;
  projectNumber?: string;
  revisionNumber?: string;
  sheetFormat?: string;
  sheetNumber?: string;
  siteIdentificationCode?: string;
  siteName?: string;
  totalNumberOfSheets?: number;
  unitIdentificationCode?: string;
  attributes?: Record<string, DexpiValue>;
  [key: string]: any;
}
`;
fs.writeFileSync(path.join(CLASSES_DIR, 'metaData.ts'), metaDataContent, 'utf-8');

// 10. Generate equipment.ts
console.log('Generating src/model/classes/equipment.ts...');
const equipmentContent = `/**
 * DEXPI Equipment, Nozzle, and Chamber interfaces.
 */

import type { DexpiObject, CustomAttributeOwner, CustomAttribute, DexpiValue, Ref, RefList } from './base';
import type { Position, Extent } from './graphics';

export interface PipingNode extends DexpiObject {
  nodeNumber?: string | number;
  nodeType?: string;
  position?: Position;
}

export interface Nozzle extends DexpiObject, CustomAttributeOwner {
  subTagName?: string;
  nodes: PipingNode[];
  chamber?: Ref;
  nominalPressureNumericalValueRepresentation?: string;
  nominalPressureRepresentation?: string;
  nominalPressureStandard?: string;
  nominalPressureTypeRepresentation?: string;
}

export interface Chamber extends DexpiObject, CustomAttributeOwner {
  chamberFunction?: string;
  chamberNumber?: string;
}

export interface TaggedPlantItem extends DexpiObject, CustomAttributeOwner {
  tagName?: string;
  plantTrain?: Ref;
  plantSystem?: Ref;
  plantArea?: Ref;
  parentStructure?: Ref;
}

export interface Equipment extends TaggedPlantItem {
  dexpiClass: string;
  componentClassUri?: string;
  nozzles: Nozzle[];
  chambers: Chamber[];
  attributes: Record<string, DexpiValue>;
  customAttributes: CustomAttribute[];
  position?: Position;
  extent?: Extent;
}
`;
fs.writeFileSync(path.join(CLASSES_DIR, 'equipment.ts'), equipmentContent, 'utf-8');

// 11. Generate piping.ts
console.log('Generating src/model/classes/piping.ts...');
const pipingContent = `/**
 * DEXPI Piping Network System, Segments, Components, and Connections.
 */

import type { DexpiObject, CustomAttributeOwner, CustomAttribute, DexpiValue, Ref } from './base';
import type { Position, Extent } from './graphics';
import type { PipingNode } from './equipment';

export interface PipingConnection extends DexpiObject {
  sourceItem?: Ref;
  sourceNode?: Ref;
  targetItem?: Ref;
  targetNode?: Ref;
}

export interface Pipe extends PipingConnection, CustomAttributeOwner {
  centerLine?: { points: { x: number; y: number }[] };
}

export type DirectPipingConnection = PipingConnection;

export interface PipingNetworkSegmentItem extends DexpiObject, CustomAttributeOwner {
  nodes?: PipingNode[];
}

export interface PipingComponent extends PipingNetworkSegmentItem {
  dexpiClass: string;
  componentClassUri?: string;
  tagName?: string;
  nodes: PipingNode[];
  attributes: Record<string, DexpiValue>;
  customAttributes: CustomAttribute[];
  position?: Position;
  extent?: Extent;
}

export interface PipeOffPageConnector extends PipingNetworkSegmentItem {
  referenceConnector?: Ref;
  connectedOffPageConnector?: Ref;
  label?: string;
}

export interface PropertyBreak extends PipingNetworkSegmentItem {
  breakClassification?: string;
}

export interface PipingNetworkSegment extends DexpiObject, CustomAttributeOwner {
  segmentNumber?: string;
  fluidCode?: string;
  nominalDiameterRepresentation?: string;
  nominalDiameterNumericalValueRepresentation?: string;
  nominalDiameterStandard?: string;
  nominalDiameterTypeRepresentation?: string;
  pipingClassCode?: string;
  operatingTemperature?: any;
  insulationType?: string;
  insulationThickness?: any;
  heatTracingType?: string;
  slope?: string;
  flowDirection?: string;
  onHold?: string;
  sourceItem?: Ref;
  sourceNode?: Ref;
  targetItem?: Ref;
  targetNode?: Ref;
  connections: PipingConnection[];
  items: PipingNetworkSegmentItem[];
  centerLine?: { points: { x: number; y: number }[] };
}

export interface PipingNetworkSystem extends DexpiObject, CustomAttributeOwner {
  lineNumber?: string;
  fluidCode?: string;
  pipingClassCode?: string;
  nominalDiameterRepresentation?: string;
  segments: PipingNetworkSegment[];
  plantTrain?: Ref;
  plantSystem?: Ref;
  plantArea?: Ref;
  parentStructure?: Ref;
}
`;
fs.writeFileSync(path.join(CLASSES_DIR, 'piping.ts'), pipingContent, 'utf-8');

// 12. Generate instrumentation.ts
console.log('Generating src/model/classes/instrumentation.ts...');
const instrumentationContent = `/**
 * DEXPI Instrumentation, Loops, Signals, and Actuators.
 */

import type { DexpiObject, CustomAttributeOwner, CustomAttribute, DexpiValue, Ref, RefList } from './base';
import type { Position, Extent } from './graphics';

export interface SignalOffPageConnector extends DexpiObject, CustomAttributeOwner {
  referenceConnector?: Ref;
  connectedOffPageConnector?: Ref;
}

export interface SignalConveyingFunction extends DexpiObject, CustomAttributeOwner {
  signalType?: string;
  sourceItem?: Ref;
  targetItem?: Ref;
  centerLine?: { points: { x: number; y: number }[] };
}

export interface Transmitter extends DexpiObject, CustomAttributeOwner {
  transmitterType?: string;
}

export interface PrimaryElement extends DexpiObject, CustomAttributeOwner {
  elementClassification?: string;
}

export interface ProcessSignalGeneratingFunction extends DexpiObject, CustomAttributeOwner {
  sensingLocation?: Ref;
  sensor?: Ref;
  transmitter?: Ref;
}

export interface ControlledActuator extends DexpiObject, CustomAttributeOwner {
  failAction?: string;
  deviceTypeName?: string;
  position?: Position;
}

export interface Positioner extends DexpiObject, CustomAttributeOwner {
  position?: Position;
}

export interface ActuatingFunction extends DexpiObject, CustomAttributeOwner {
  controlledActuator?: Ref;
  positioner?: Ref;
  position?: Position;
}

export interface ActuatingElectricalFunction extends DexpiObject, CustomAttributeOwner {
  position?: Position;
}

export interface ActuatingSystem extends DexpiObject, CustomAttributeOwner {
  actuatingSystemNumber?: string;
  actuatingFunctions: ActuatingFunction[];
  controlledActuators: ControlledActuator[];
  position?: Position;
}

export interface ProcessSignalGeneratingSystem extends DexpiObject, CustomAttributeOwner {
  systemNumber?: string;
}

export interface ProcessInstrumentationFunction extends DexpiObject, CustomAttributeOwner {
  dexpiClass?: string;
  componentClassUri?: string;
  processInstrumentationFunctionNumber?: string;
  processInstrumentationFunctionCategory?: string;
  processInstrumentationFunctions?: string;
  location?: string;
  panelIdentificationCode?: string;
  processSignalGeneratingFunctions: ProcessSignalGeneratingFunction[];
  signalConveyingFunctions: SignalConveyingFunction[];
  actuatingFunctions: ActuatingFunction[];
  signalConnectors: SignalOffPageConnector[];
  actuatingElectricalFunctions: ActuatingElectricalFunction[];
  position?: Position;
}

export interface InstrumentationLoopFunction extends DexpiObject, CustomAttributeOwner {
  loopNumber?: string;
  processInstrumentationFunctions?: RefList;
}
`;
fs.writeFileSync(path.join(CLASSES_DIR, 'instrumentation.ts'), instrumentationContent, 'utf-8');

// 13. Generate conceptualModel.ts
console.log('Generating src/model/classes/conceptualModel.ts...');
const conceptualModelContent = `/**
 * DEXPI ConceptualModel container.
 */

import type { DexpiObject } from './base';
import type { ActuatingSystem, InstrumentationLoopFunction, ProcessInstrumentationFunction, ProcessSignalGeneratingSystem } from './instrumentation';
import type { MetaData } from './metaData';
import type { PipingNetworkSystem } from './piping';
import type { PlantStructureItem } from './plantStructure';
import type { TaggedPlantItem } from './equipment';

export interface ConceptualModel extends DexpiObject {
  actuatingSystems: ActuatingSystem[];
  instrumentationLoopFunctions: InstrumentationLoopFunction[];
  metaData?: MetaData;
  pipingNetworkSystems: PipingNetworkSystem[];
  plantStructureItems: PlantStructureItem[];
  processInstrumentationFunctions: ProcessInstrumentationFunction[];
  processSignalGeneratingSystems: ProcessSignalGeneratingSystem[];
  taggedPlantItems: TaggedPlantItem[];
}
`;
fs.writeFileSync(path.join(CLASSES_DIR, 'conceptualModel.ts'), conceptualModelContent, 'utf-8');

// 14. Generate dexpiModel.ts
console.log('Generating src/model/classes/dexpiModel.ts...');
const dexpiModelContent = `/**
 * Root DEXPI Model interface.
 */

import type { DexpiObject } from './base';
import type { ConceptualModel } from './conceptualModel';
import type { Diagram, ShapeCatalogue } from './graphics';

export interface DexpiModel extends DexpiObject {
  conceptualModel: ConceptualModel;
  diagram?: Diagram;
  shapeCatalogues: ShapeCatalogue[];
  exportDateTime?: string;
  originatingSystemName?: string;
  originatingSystemVendorName?: string;
  originatingSystemVersion?: string;
}
`;
fs.writeFileSync(path.join(CLASSES_DIR, 'dexpiModel.ts'), dexpiModelContent, 'utf-8');

// 15. Generate classes/index.ts
console.log('Generating src/model/classes/index.ts...');
const classesIndexContent = `export * from './base';
export * from './dataTypes';
export * from './enumerations';
export * from './graphics';
export * from './plantStructure';
export * from './metaData';
export * from './equipment';
export * from './piping';
export * from './instrumentation';
export * from './conceptualModel';
export * from './dexpiModel';
`;
fs.writeFileSync(path.join(CLASSES_DIR, 'index.ts'), classesIndexContent, 'utf-8');

// 16. Generate registry.ts
console.log('Generating src/model/registry.ts...');
const simplifiedSchema = {};
for (const [clsName, clsInfo] of Object.entries(schema.classes)) {
  const fields = {};
  for (const [fName, fMeta] of Object.entries(clsInfo.fields)) {
    fields[fName] = {
      category: fMeta.category || undefined,
      isList: fMeta.isList,
      required: fMeta.required,
      type: fMeta.type,
    };
  }
  simplifiedSchema[clsName] = fields;
}

const registryContent = `/**
 * [GENERATED BY scripts/gen-model.mjs - DO NOT EDIT MANUALLY]
 * pyDEXPI 1.2.0 Field Registry (SCHEMA) across all classes.
 */

export interface FieldMeta {
  category?: 'composition' | 'reference' | 'data';
  isList: boolean;
  required: boolean;
  type?: string;
}

export const SCHEMA: Record<string, Record<string, FieldMeta>> = ${JSON.stringify(simplifiedSchema, null, 2)};

export function getFieldMeta(className: string, fieldName: string): FieldMeta | undefined {
  const clsFields = SCHEMA[className];
  if (clsFields && clsFields[fieldName]) {
    return clsFields[fieldName];
  }
  return undefined;
}
`;
fs.writeFileSync(path.join(MODEL_DIR, 'registry.ts'), registryContent, 'utf-8');

console.log('Done! Successfully generated model types and field registry.');
